# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a525e85e4453e2b11943d0015c59058e0a564f2bc0dc49e9308acfa8af8e99290d4750592d7f379bfb3782f83b2923ce780ffae471f110ffad26110b017ad9ba

test:
  secret_key_base: 927cb59ef9cd3cab2bda7ffe871e940809761929750f79d389a86206eb62d22402510b910fffadb01991f8ac5e618eb68dd991fa0eb7c8726c6d3c7bac243f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
